//combine js files in koala

// @koala-append "../javascript/alert.js"
// @koala-append "../javascript/badges-demo.js"
// @koala-append "../javascript/bar-graph.js"
// @koala-append "../javascript/bookmarklet.js"
// @koala-append "../javascript/breadcrumb.js"
// @koala-append "../javascript/carousel.js"
// @koala-append "../javascript/chips.js"
// @koala-append "../javascript/collapse.js"
// @koala-append "../javascript/demo.js"
// @koala-append "../javascript/DEMOONLYwtf.js"
// @koala-append "../javascript/dropdown.js"
// @koala-append "../javascript/forminputs.js"
// @koala-append "../javascript/herald.js"
// @koala-append "../javascript/loader.js"
// @koala-append "../javascript/modals.js"
// @koala-append "../javascript/gallery.js"
// @koala-append "../javascript/progressbarbtn.js"
// @koala-append "../javascript/scrollspy-nav.js"
// @koala-append "../javascript/single-input-form.js"
// @koala-append "../javascript/sticky-nav.js"
// @koala-append "../javascript/tabs.js"
// @koala-append "../javascript/inline-note.js"
// @koala-append "../javascript/dotValid.js"
// @koala-append "load-eureka-display.js"
// @koala-append "prism.js"

